function Diagnosis = GetDiagnosis
Diagnosis = {...
    'Dextro-Transposition of the Great Arteries',1;...
    'Levo-Transposition of the Great Arteries',2;...
    'Pulmonary Atresia',3;...
    'Triscupid Atresia',4;...
    'Aortic Artesia',6;...
    'Mitral Artesia',7;...
    'Ebstiens Anomaly',8;...
    'Coarctation of the Aorta',9;...
    'Ventricular Septal Defect',10;...
    'Atrial Septal Defect',11;...
    'Hypoplastic Left Heart Syndrome',12;...
    'Hypoplastic Right Heart Syndrome', 13;...
    'Double Outlet Left Ventricle', 14;...
    'Double Outlet Right Ventricle', 15;...
    'Double Inlet Left Ventricle', 16;...
    'Double Inlet Right Ventricle', 17;...
    'Aortic Stenosis', 18;...
    'Marfans syndrome', 19;...
    'Atrioventricular Canal Defect', 20;...
    'Bicuspid Aortic Valve', 21;...
    'Complete Congenital Heart Block', 22;...
    'Dextrocardia', 23;...
    'Coronary Artery Anomaly',24;...
    'Double Chamber Right Ventricle',25;...
    'Double Aortic Arch',26;...
    'Eisenmengers Syndrome',27;...
    'Holmes Heart', 28;...
    'Interupted Aortic Arch', 29;...
    'Pulmonary Stenosis', 30;...
    'Total Anomalous Pulmonary Venous Drainage', 31;...
    'Tetralogy of Fallot', 32;...
    'Partially Anomalous Pulmonary Venous Return', 33;....
    'Taussig–Bing syndrome', 34;...
    'Persistent truncus arteriosus', 35;...
    'Tricuspid Stenosis', 36;... 
    }
end